// ═══════════════════════════════════════════════════════════════
// Astra — Archer class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.299Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Archer',
  emoji: '🏹',
    lore: 'Precision over power. Every arrow finds its mark.',
    maxBonuses: { hp: 60, atk: 45, def: 8, speed: 25, maxEnergy: 30 },
    skills: [
      { name: 'Eagle Eye',     type: 'passive', maxPotency: 25,  desc: 'Crit chance +{p}%' },
      { name: 'Barrage',       type: 'damage',  maxPotency: 220, desc: 'Fires {p}% ATK across 3 rapid shots' },
      { name: "Hunter's Mark", type: 'debuff',  maxPotency: 30,  desc: 'Target takes {p}% more damage for 3 turns' },
    ],
};
