// ═══════════════════════════════════════════════════════════════
// Astra — Knight class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.300Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Knight',
  emoji: '🛡️',
    lore: 'The wall between the weak and the storm.',
    maxBonuses: { hp: 180, atk: 15, def: 45, speed: -5, maxEnergy: 25 },
    skills: [
      { name: 'Fortress Stance', type: 'buff',    maxPotency: 50,  desc: 'DEF +{p}% for 3 turns' },
      { name: 'Counterguard',    type: 'passive', maxPotency: 30,  desc: 'Reflects {p}% of blocked damage' },
      { name: 'Last Stand',      type: 'buff',    maxPotency: 80,  desc: 'Below 20% HP: ATK +{p}%' },
    ],
};
