// ═══════════════════════════════════════════════════════════════
// Astra — Mage class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.299Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Mage',
  emoji: '🔮',
    lore: 'Knowledge is the sharpest weapon.',
    maxBonuses: { hp: 45, atk: 55, def: 5, speed: 10, maxEnergy: 70, magicPower: 50 },
    skills: [
      { name: 'Arcane Burst', type: 'damage',  maxPotency: 300, desc: 'Deals {p}% Magic Power as arcane damage' },
      { name: 'Mana Shield',  type: 'buff',    maxPotency: 40,  desc: 'Absorbs {p}% of next hit using energy' },
      { name: 'Spell Surge',  type: 'passive', maxPotency: 20,  desc: 'Every 3rd skill deals {p}% bonus damage' },
    ],
};
