// ═══════════════════════════════════════════════════════════════
// Astra — Monk class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.300Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Monk',
  emoji: '☯️',
    lore: 'The body is the temple. The mind is the weapon.',
    maxBonuses: { hp: 100, atk: 25, def: 25, speed: 20, maxEnergy: 40 },
    skills: [
      { name: 'Inner Peace', type: 'heal',    maxPotency: 25,  desc: 'Restore {p}% max HP' },
      { name: 'Iron Palm',   type: 'damage',  maxPotency: 200, desc: 'Deals {p}% ATK, ignores {p/4}% DEF' },
      { name: 'Balance',     type: 'passive', maxPotency: 15,  desc: 'Each turn restores {p} HP' },
    ],
};
