// ═══════════════════════════════════════════════════════════════
// Astra — Rogue class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.299Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Rogue',
  emoji: '🗡️',
    lore: 'Strike first. Strike true. Vanish before they fall.',
    maxBonuses: { hp: 50, atk: 40, def: 6, speed: 40, maxEnergy: 35 },
    skills: [
      { name: 'Shadowstep', type: 'damage',  maxPotency: 250, desc: 'Guaranteed crit hit for {p}% ATK' },
      { name: 'Evasion',    type: 'passive', maxPotency: 20,  desc: 'Dodge chance +{p}%' },
      { name: 'Hemorrhage', type: 'debuff',  maxPotency: 40,  desc: 'Inflicts bleed: {p}% ATK per turn for 4 turns' },
    ],
};
