// ═══════════════════════════════════════════════════════════════
// Astra — Shaman class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.300Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Shaman',
  emoji: '🌀',
    lore: 'Channels forces beyond human comprehension.',
    maxBonuses: { hp: 70, atk: 30, def: 12, speed: 8, maxEnergy: 60, magicPower: 35 },
    skills: [
      { name: 'Spirit Link',     type: 'buff',    maxPotency: 20,  desc: 'Party ATK +{p}% for 2 turns' },
      { name: 'Hex',             type: 'debuff',  maxPotency: 35,  desc: 'Target DEF -{p}% for 3 turns' },
      { name: 'Ancestral Wrath', type: 'damage',  maxPotency: 260, desc: 'Deals {p}% of combined ATK + Magic Power' },
    ],
};
