// ═══════════════════════════════════════════════════════════════
// Astra — Warlord class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.301Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Warlord',
  emoji: '🏴',
    lore: 'Leads from the front. Never from safety.',
    maxBonuses: { hp: 100, atk: 40, def: 25, speed: 10, maxEnergy: 30 },
    skills: [
      { name: 'War Cry',     type: 'buff',    maxPotency: 35,  desc: 'Party ATK +{p}% and DEF +15% for 3 turns' },
      { name: 'Cleave',      type: 'damage',  maxPotency: 160, desc: 'Hits all enemies for {p}% ATK' },
      { name: 'Iron Will',   type: 'passive', maxPotency: 30,  desc: 'Cannot be killed below 1 HP for 1 turn per fight' },
    ],
};
