// ═══════════════════════════════════════════════════════════════
// Astra — Warrior class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.298Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Warrior',
  emoji: '⚔️',
    lore: 'Masters of direct combat. Unyielding in battle.',
    maxBonuses: { hp: 120, atk: 35, def: 20, speed: 5, maxEnergy: 20 },
    skills: [
      { name: 'Battle Cry',   type: 'buff',    maxPotency: 30,  desc: 'Boosts ATK by {p}% for 3 turns' },
      { name: 'Shield Bash',  type: 'damage',  maxPotency: 180, desc: 'Deals {p}% ATK as damage, stuns 1 turn' },
      { name: 'Iron Resolve', type: 'passive', maxPotency: 15,  desc: 'Reduces all damage taken by {p}%' },
    ],
};
