// ═══════════════════════════════════════════════════════════════
// Astra — Assassin class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.300Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Assassin',
  emoji: '🥷',
    lore: 'The last thing you see is your own reflection.',
    maxBonuses: { hp: 40, atk: 50, def: 4, speed: 50, maxEnergy: 40, critChance: 10 },
    skills: [
      { name: 'Death Mark',   type: 'debuff',  maxPotency: 40,  desc: 'Target takes {p}% more damage, stacks 3x' },
      { name: 'Vanish',       type: 'buff',    maxPotency: 100, desc: 'Dodge all attacks for 1 turn' },
      { name: 'Backstab',     type: 'damage',  maxPotency: 350, desc: 'From stealth: {p}% ATK guaranteed crit' },
    ],
};
