// ═══════════════════════════════════════════════════════════════
// Astra — BloodKnight class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.301Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'BloodKnight',
  emoji: '🩸',
    lore: 'Every wound is a weapon. Every scar, an advantage.',
    maxBonuses: { hp: 110, atk: 45, def: 20, speed: 10, maxEnergy: 30, lifesteal: 8 },
    skills: [
      { name: 'Crimson Blade', type: 'damage',  maxPotency: 200, desc: 'Deals {p}% ATK + steals {p/4}% of target max HP' },
      { name: 'Blood Armor',   type: 'buff',    maxPotency: 40,  desc: 'Converts {p}% of damage taken into HP recovery next turn' },
      { name: 'Hemorrhage',    type: 'passive', maxPotency: 15,  desc: 'All physical attacks apply bleed: {p}% ATK per turn' },
    ],
};
