// ═══════════════════════════════════════════════════════════════
// Astra — Elementalist class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.302Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Elementalist',
  emoji: '🌊',
    lore: 'Commands fire, ice, and lightning simultaneously.',
    maxBonuses: { hp: 50, atk: 30, def: 8, speed: 10, maxEnergy: 80, magicPower: 65 },
    skills: [
      { name: 'Elemental Burst', type: 'damage',  maxPotency: 320, desc: 'Deals {p}% Magic Power — switches element each cast' },
      { name: 'Storm Shield',    type: 'buff',    maxPotency: 35,  desc: 'Elemental barrier: absorbs {p}% of magic damage' },
      { name: 'Elemental Mastery',type:'passive', maxPotency: 25,  desc: 'All elemental damage deals {p}% bonus damage' },
    ],
};
