// ═══════════════════════════════════════════════════════════════
// Astra — Necromancer class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.301Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Necromancer',
  emoji: '💀',
    lore: 'Death is not a limit. It is a resource.',
    maxBonuses: { hp: 55, atk: 35, def: 8, speed: 5, maxEnergy: 90, magicPower: 55 },
    skills: [
      { name: 'Corpse Explosion', type: 'damage',  maxPotency: 280, desc: 'Destroys a corpse for {p}% Magic Power AoE damage' },
      { name: 'Soul Drain',       type: 'damage',  maxPotency: 150, desc: 'Drains {p}% target HP, restores half to you' },
      { name: 'Bone Wall',        type: 'buff',    maxPotency: 60,  desc: 'Summons barrier absorbing {p}% of incoming damage' },
    ],
};
