// ═══════════════════════════════════════════════════════════════
// Astra — Paladin class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.300Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Paladin',
  emoji: '✨',
    lore: 'Justice given flesh. Mercy given limits.',
    maxBonuses: { hp: 150, atk: 20, def: 35, speed: 5, maxEnergy: 30, magicPower: 25 },
    skills: [
      { name: 'Holy Strike',   type: 'damage',  maxPotency: 180, desc: 'Deals {p}% ATK as holy damage, heals 20% of it' },
      { name: 'Divine Shield', type: 'buff',    maxPotency: 50,  desc: 'Absorbs {p}% of incoming damage for 2 turns' },
      { name: 'Aura of Purity',type: 'passive', maxPotency: 15,  desc: 'Party takes {p}% less magic damage' },
    ],
};
