// ═══════════════════════════════════════════════════════════════
// Astra — Ranger class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.300Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Ranger',
  emoji: '🌲',
    lore: 'Master of terrain, trap, and distance.',
    maxBonuses: { hp: 80, atk: 35, def: 15, speed: 30, maxEnergy: 35 },
    skills: [
      { name: 'Aimed Shot',    type: 'damage',  maxPotency: 200, desc: 'Charged shot: {p}% ATK + 50% crit chance' },
      { name: 'Snare Trap',    type: 'debuff',  maxPotency: 2,   desc: 'Stuns target for {p} turn(s)' },
      { name: 'Tracking',      type: 'passive', maxPotency: 20,  desc: 'Enemy DEF revealed — ignores {p}% of it' },
    ],
};
