// ═══════════════════════════════════════════════════════════════
// Astra — SpellBlade class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.301Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'SpellBlade',
  emoji: '⚡',
    lore: 'The blade sings. The spell answers.',
    maxBonuses: { hp: 70, atk: 40, def: 15, speed: 20, maxEnergy: 50, magicPower: 35 },
    skills: [
      { name: 'Spell Edge',   type: 'damage',  maxPotency: 220, desc: 'Melee hit infused with magic: {p}% ATK + Magic Power' },
      { name: 'Arcane Blade', type: 'passive', maxPotency: 25,  desc: 'Each physical hit has {p}% chance to trigger a free spell' },
      { name: 'Mana Slash',   type: 'damage',  maxPotency: 180, desc: 'Drains {p}% of target energy as bonus damage' },
    ],
};
