// ═══════════════════════════════════════════════════════════════
// Astra — Senku class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.302Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Senku',
  emoji: '⚗️',
    lore: 'The 10 billion% genius. Science is the ultimate power — and you are its voice.',
    maxBonuses: {
      hp: 280,
      atk: 75,
      def: 45,
      speed: 65,
      maxEnergy: 110,
      magicPower: 70,
      critChance: 15,
      lifesteal: 10,
    },
    skills: [
      { name: 'Nitro Burst',     type: 'damage',  maxPotency: 380, desc: 'Deals {p}% ATK as science damage, applies burn for 3 turns' },
      { name: '10 Billion%',     type: 'damage',  maxPotency: 500, desc: 'Ultimate genius form: {p}% ATK, guaranteed crit, ignores 50% of target DEF' },
      { name: 'Stone Formula',   type: 'damage',  maxPotency: 320, desc: 'Petrifying compound: {p}% ATK + target is frozen for 2 turns' },
      { name: 'Revival Serum',   type: 'heal',    maxPotency: 60,  desc: 'Restore {p}% max HP + remove all debuffs' },
      { name: 'Senku Overdrive', type: 'buff',    maxPotency: 100, desc: 'ATK +{p}% for 5 turns, all skills cost 0 energy' },
      { name: 'Perseus Cannon',  type: 'damage',  maxPotency: 700, desc: 'Divine-tier beam: {p}% combined ATK + Magic Power, pierces all defenses' },
      { name: 'Scientific Genius',   type: 'passive', maxPotency: 50,  desc: 'All skill damage +{p}% (best in game)' },
      { name: 'Immortal Formula',    type: 'passive', maxPotency: 30,  desc: 'Heal {p}% of all damage dealt back as HP' },
      { name: '10 Billion% Resolve', type: 'passive', maxPotency: 100, desc: 'Below 30% HP: ATK +{p}%, damage taken -50%, 100% crit' },
    ],
};
