// ═══════════════════════════════════════════════════════════════
// Astra — Chronomancer class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.302Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Chronomancer',
  emoji: '⏳',
    lore: 'Time is merely a suggestion.',
    maxBonuses: { hp: 60, atk: 30, def: 10, speed: 35, maxEnergy: 75, magicPower: 45 },
    skills: [
      { name: 'Time Stop',     type: 'debuff',  maxPotency: 2,   desc: 'Freezes target for {p} turn(s). They cannot act.' },
      { name: 'Rewind',        type: 'heal',    maxPotency: 40,  desc: 'Restores {p}% HP to self and removes 1 debuff' },
      { name: 'Haste',         type: 'buff',    maxPotency: 50,  desc: 'SPD +{p}% for 3 turns, grants second action next turn' },
    ],
};
