// ═══════════════════════════════════════════════════════════════
// Astra — Devourer class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.302Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Devourer',
  emoji: '🕳️',
    lore: 'Grows stronger with each kill. Has never stopped eating.',
    maxBonuses: { hp: 160, atk: 55, def: 15, speed: 10, maxEnergy: 30, lifesteal: 12 },
    skills: [
      { name: 'Consume',       type: 'damage',  maxPotency: 200, desc: 'Deals {p}% ATK + absorbs {p/5}% of target max HP permanently' },
      { name: 'Hunger',        type: 'passive', maxPotency: 20,  desc: 'Each kill increases ATK by {p} permanently (this run)' },
      { name: 'Void Maw',      type: 'damage',  maxPotency: 260, desc: 'Pulls enemies inward: {p}% ATK, ignores dodge' },
    ],
};
