// ═══════════════════════════════════════════════════════════════
// Astra — Phantom class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.302Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Phantom',
  emoji: '👁️',
    lore: 'Exists between the living and the dead.',
    maxBonuses: { hp: 80, atk: 55, def: 8, speed: 45, maxEnergy: 50, magicPower: 30 },
    skills: [
      { name: 'Phase Shift',   type: 'buff',    maxPotency: 80,  desc: 'Phases through attacks for 1 turn, counters for {p}% ATK' },
      { name: 'Soul Rend',     type: 'damage',  maxPotency: 300, desc: 'Bypasses all DEF: deals {p}% ATK directly to HP' },
      { name: 'Phantom Mark',  type: 'passive', maxPotency: 20,  desc: 'After entering phase, next attack ignores {p}% DEF' },
    ],
};
