// ═══════════════════════════════════════════════════════════════
// Astra — Asset Manager
//
// Single source of truth for image lookups, lore, and stats.
// Every command that wants to display an item/monster/pet/etc.
// goes through here so adding an image or a line of lore is one
// change, not 20.
//
// Layout on disk:
//   assets/images/items/<rarity>/<name>.png
//   assets/images/pets/<key>.png
//   assets/images/monsters/<name>.png
//   assets/images/bosses/<name>.png
//   assets/images/artifacts/<name>.png
//   assets/images/classes/<tier>/<name>.png
//   assets/images/skins/<rarity>/<key>.png
//
// Fallback chain (no image): render a colored card with emoji
// and stats text. The bot never goes silent just because art
// hasn't been generated yet.
// ═══════════════════════════════════════════════════════════════

'use strict';

const fs = require('fs');
const path = require('path');

const ASSET_ROOT = path.join(__dirname, '..', '..', 'assets', 'images');

// ── Cache: { key: { path, exists, mtime } } ──────────────────
const _cache = new Map();

function safeExists(p) {
  try { return fs.existsSync(p); } catch (_) { return false; }
}

// Resolve an image path. Returns absolute path or null.
function findImage(relativePath) {
  const abs = path.isAbsolute(relativePath) ? relativePath : path.join(ASSET_ROOT, relativePath);
  if (_cache.has(abs)) return _cache.get(abs);
  const exists = safeExists(abs);
  const result = { path: abs, exists };
  _cache.set(abs, result);
  return result;
}

// Invalidate the cache (call after generating a new image).
function invalidateCache(key) {
  if (key) _cache.delete(key);
  else _cache.clear();
}

// ── Slugify: turn "Wooden Club" → "wooden_club" ─────────────
function slugify(name) {
  return String(name)
    .toLowerCase()
    .replace(/['"`]/g, '')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

// ── 1. Item lookup ───────────────────────────────────────────
const ITEM_RARITY_COLORS = {
  common:    { bg: '#1c1c1c', accent: '#9aa3ad',  emoji: '⚪' },
  uncommon:  { bg: '#0d2a1a', accent: '#3ddc84',  emoji: '🟢' },
  rare:      { bg: '#0d1f3a', accent: '#4d8bff',  emoji: '🔵' },
  epic:      { bg: '#2a0d3a', accent: '#b15bff',  emoji: '🟣' },
  legendary: { bg: '#3a2a0d', accent: '#ffb84d',  emoji: '🟠' },
  mythic:    { bg: '#3a0d1a', accent: '#ff4d6d',  emoji: '🔴' },
};

function getItemImagePath(name, rarity) {
  const slug = slugify(name);
  return findImage(path.join('items', rarity, `${slug}.png`));
}

// ── 2. Pet lookup ────────────────────────────────────────────
function getPetImagePath(key) {
  return findImage(path.join('pets', `${key}.png`));
}

// ── 3. Monster lookup ────────────────────────────────────────
function getMonsterImagePath(name) {
  return findImage(path.join('monsters', `${slugify(name)}.png`));
}

// ── 4. Boss lookup ───────────────────────────────────────────
function getBossImagePath(name) {
  return findImage(path.join('bosses', `${slugify(name)}.png`));
}

// ── 5. Artifact lookup ───────────────────────────────────────
function getArtifactImagePath(name) {
  return findImage(path.join('artifacts', `${slugify(name)}.png`));
}

// ── 6. Class lookup ──────────────────────────────────────────
function getClassImagePath(name, tier) {
  return findImage(path.join('classes', tier, `${slugify(name)}.png`));
}

// ── 7. Skin lookup ───────────────────────────────────────────
function getSkinImagePath(key, rarity) {
  return findImage(path.join('skins', rarity, `${key}.png`));
}

// ═══════════════════════════════════════════════════════════════
// LORE DATABASE — short, evocative blurbs for every entity
//
// The lore is what makes the two-message card feel like a
// trading card. Generated by the lore generator (assets/lore.js)
// but seeded here for stability. If an entry is missing, the
// system falls back to a procedurally generated blurb.
// ═══════════════════════════════════════════════════════════════

const LORE = {
  // Items
  items: {
    'Wooden Club':          'A splintered oak branch, gripped by desperate goblins for centuries. Heavy enough to crack a skull — light enough to forget you dropped it.',
    'Bone Dagger':          'A short blade carved from a giant rat\'s femur. The runes along the spine hum faintly when its wielder is enraged.',
    'Iron Sword':           'A trustworthy iron longsword, the kind every aspiring hunter carries into their first gate. The edge never dulls if you keep it oiled.',
    'Mana Stone Dragon Greatsword': 'Forged from a single shard of an Elder Dragon\'s crystallized heart. Each swing releases a chord of pure mana that shatters the air itself.',
    'Dragon King Sovereign Blade': 'A blade said to be the first weapon ever drawn in the age of dragons. The King carved it from his own horn after slaying the gods that mocked his mortality.',
    'Shadow Monarch Fragment I':  'A piece of the Shadow Monarch\'s essence, crystallized into armor. The wearer can phase through solid matter three times before the fragment dissolves.',
    'Shadow Monarch Fragment V':  'The fifth and most powerful fragment, pulsing with sovereign void. Whoever binds it earns the Monarch\'s gaze — for good or ill.',
  },

  // Pets
  pets: {
    slime_pup:       'A wobbly green companion that follows its owner everywhere. Bounces when happy. Splats when sad. Smells like rain.',
    flame_fox:       'A small fox wreathed in eternal flame. Its tail burns in eight different colors when it sleeps. Warm to the touch, cool to the soul.',
    shadow_wolf:     'A black-furred wolf pup that walks on the shadows themselves. Howls at the moon — but only when no one is looking.',
    lightning_drake: 'A tiny electric dragon that crackles when excited. Has been known to short-circuit palace lighting when startled.',
    forest_sprite:   'A leaf-winged fae that tends to wounded trees. Carries acorns for emergencies. Mostly an excuse to nap in moss.',
    wind_fairy:      'A gust of wind given wings. Cannot be held, but sometimes rests on shoulders. Smells like spring.',
    crystal_phoenix:  'A phoenix no bigger than a sparrow, with feathers of living quartz. Cries in musical notes. Refuses to fly in the rain.',
    mud_crawler:     'A friendly mud elemental that purrs when petted. Will track mud everywhere. Worth it.',
    void_bat:        'A purple bat that hangs upside down in the user\'s shadow. Wings folded, it looks like a small cloak with eyes.',
    stone_golem_baby:'A fist-sized baby golem that toddles around. The stone of its body is warm to the touch. Adores headpats.',
    king_slime:      'A regal slime with a tiny golden crown. Rules all slime-kind from atop a mossy throne. Loyal to its bonded hunter only.',
    nine_tail_fox:   'A white fox with nine flowing tails, each one a different elemental affinity. Watches its bonded with ancient, knowing eyes.',
    ancient_treant:  'A small sapling that walks on tiny roots. Old beyond its appearance — has memories from the first forests. Sleeps standing up.',
    gold_beetle:     'A beetle with a carapace of pure Nexus. When frightened, it buries itself and plays dead. Collects shiny things in a hidden burrow.',
  },

  // Monsters (short origin blurbs)
  monsters: {
    'Goblin':          'Small, vicious, and cunning in numbers. Goblins have raided human caravans since the first gates opened. The weak ones die young; the survivors become terrifying.',
    'Goblin Shaman':   'Goblin elders who have bargained with the spirits of rot. Their hexes are crude but effective — most hunters underestimate them, once.',
    'Skeleton':        'A re-animated pile of bones, held together by a fading fragment of grudging soul-fire. The cheapest minion in any necromancer\'s army.',
    'Green Slime':     'A puddle with ambitions. Eats anything organic. Reproduces by splitting. Considered the dungeon\'s cleanup crew.',
    'Dire Wolf':       'Once a normal wolf, twisted by mana saturation. Hunts in packs. The alpha wears the skulls of its rivals as trophies.',
    'Stone Golem':     'Carved by forgotten mountain-dwarf priests to guard their abandoned temples. Two hundred years later, it still guards.',
    'Orc Warrior':     'Born under a red moon, raised on war drums. An orc\'s first kill is their coming-of-age; their last is carved into their tombstone.',
    'Dark Elf':        'Exiled from their sky-cities for consorting with void-magic. They now haunt the forest undergrowth, daggers drawn, ready to settle old grudges.',
    'Wyvern':          'Lesser cousin of the true dragons, but no less dangerous. Their stinger carries a venom that crystallizes blood in seconds.',
    'Soul Reaper':     'A wraith that has collected so many souls it has begun to think. Wears its victims as trophies. Speaks in echoes.',
  },

  // Artifacts
  artifacts: {
    'Excalibur':          'The legendary sword of the chosen king. Only the pure of heart can lift it. Everyone else gets a splintered palm and a lesson.',
    'Mjolnir':            'The god-hammer. Returns to its thrower when summoned. Heavy as sin, light as a feather to the worthy.',
    'Frostmourne':        'A rune blade that drinks the warmth of everything it cuts. Its wielder is granted power — at the cost of all feeling.',
    'Gungnir':            'The Spear of Heaven. Never misses its mark. Throws itself. Comes back. Throws itself again. The wielder eventually gets bored.',
    'Heart of the Phoenix':'A crystallized heart that beats once every ten thousand years. The owner is reborn in flame upon death — once.',
    'Infinity Gauntlet':  'Six slots, six stones. Reality bends at the wielder\'s whim. Side effect: occasional finger-itching for no reason.',
  },

  // Classes
  classes: {
    'Warrior':    'A simple, sturdy fighter. Hits things until they stop moving. Has never lost an argument with a sword.',
    'Mage':       'A scholar of the arcane. Trades physical toughness for the ability to set rooms on fire from across the hall.',
    'Rogue':      'A shadow in the alley, a knife in the back, a sarcastic comment in every fight. Trusts no one; surprisingly loyal to those they do.',
    'Archer':     'An eye that never blinks, a finger that never trembles. Has strong opinions about crossbows versus bows.',
    'Knight':     'An armored oath. The kind of person who runs toward danger so others can run away. Wakes up early, drinks black coffee, hits things.',
    'Monk':       'Fists of iron, heart of calm. Channels mana through the body, not the air. Best at parties — always willing to demonstrate the pressure-point trick.',
    'Shaman':     'A bridge between the living and the spirit world. Speaks to ancestors for a living. Has strong opinions on which mushrooms are edible.',
    'Warlord':    'A battlefield general, a master of mass combat. Summons banners that inspire allies to feats they didn\'t know they could do.',
    'Assassin':   'A whisper, then a thud. Specializes in single-target elimination. Has a strong work ethic and a strict no-eyewitness policy.',
    'Paladin':    'A knight who chose the light. Wields holy power with the same discipline a surgeon uses a scalpel. Cannot resist helping old ladies across streets.',
    'BloodKnight':'A knight who chose the dark instead. Wields blood-magic, drains life from enemies. The armor is alive. It is hungry.',
    'Elementalist':'A mage who refused to pick one element. Calls down fire, frost, and lightning on the same target. Opponents get dizzy.',
    'Necromancer':'A mage who befriended death. Speaks to corpses. Corpses answer. The smell is mostly bearable with practice.',
    'Ranger':     'An archer who learned to love the forest. Tracks monsters by smell, fights with companion beasts. Owns at least four knives.',
    'SpellBlade': 'A mage-warrior hybrid. Casts with one hand, slashes with the other. Wears armor that hums when spells are charging.',
    'Berserker':  'A warrior who gave up defense for raw power. The rage is a tide — when it rises, nothing stands. The downside: when it falls, you\'re tired.',
    'Chronomancer':'A mage who learned to read the river of time. Slows enemies, speeds allies. Has strong opinions about which way clocks should turn.',
    'Devourer':   'A warrior who eats the souls of the fallen. Gets stronger with each kill. Has trouble with regular meals afterward.',
    'Phantom':    'A rogue-mage hybrid. Walks through walls, casts from impossible angles. Cannot hold a coffee without spilling it for the same reason.',
    'Healer':     'A mage who learned to mend instead of burn. Stands behind the front line and keeps everyone else alive. Never gets thanked.',
    'DragonKnight':'A knight who bound a dragon to their soul. Their armor scales in combat. Their breath is fire. Their temperament is worse.',
    'ShadowDancer':'A rogue who learned to dance with the shadows themselves. Strikes from impossible angles. Has a fondness for candles.',
    'Summoner':   'A mage who learned to call friends. Has six to twelve active summons at any time. The neighbors have complained.',
    'Senku':      'The Divine. A scientist-recluse bound by logic, not magic. Wields the power of the ten-billion-percent brain. Looks like a high schooler. Definitely not a high schooler.',
  },
};

// ═══════════════════════════════════════════════════════════════
// Procedural lore generator
//
// If we don't have a hand-written lore for an entity, generate
// a believable Astra-flavored blurb from its name + type.
// ═══════════════════════════════════════════════════════════════

const ELEMENT_HINTS = {
  fire:    ['burning', 'flame', 'molten', 'ember', 'ash', 'scorch'],
  frost:   ['frozen', 'rime', 'glacial', 'winter', 'icy', 'shiver'],
  shadow:  ['shadow', 'void', 'dark', 'night', 'shroud', 'whisper'],
  light:   ['radiant', 'shining', 'divine', 'golden', 'dawn', 'halo'],
  nature:  ['leaf', 'root', 'thorn', 'forest', 'sap', 'verdant'],
  storm:   ['thunder', 'lightning', 'storm', 'spark', 'crack', 'tempest'],
  blood:   ['blood', 'crimson', 'cursed', 'bleeding', 'pulsing'],
  death:   ['bone', 'wraith', 'ghost', 'spirit', 'skull', 'specter'],
  crystal: ['crystal', 'gem', 'shard', 'prism', 'faceted'],
  dragon:  ['dragon', 'wyrm', 'drake', 'scale', 'claw', 'horn'],
};

function detectElement(text) {
  const lower = String(text).toLowerCase();
  for (const [k, hints] of Object.entries(ELEMENT_HINTS)) {
    if (hints.some((h) => lower.includes(h))) return k;
  }
  return null;
}

// Detect item "type" by name pattern
function detectItemType(name) {
  const n = String(name).toLowerCase();
  if (/(sword|blade|saber|katana|rapier|scimitar|dagger|knife)/.test(n)) return 'sword';
  if (/(axe|cleaver|hatchet)/.test(n)) return 'axe';
  if (/(bow|arrow|quiver)/.test(n)) return 'bow';
  if (/(staff|wand|rod|orb|tome|book|grimoire)/.test(n)) return 'magic';
  if (/(mace|club|hammer|maul)/.test(n)) return 'blunt';
  if (/(lance|spear|pike|halberd|trident)/.test(n)) return 'polearm';
  if (/(scythe|sickle)/.test(n)) return 'scythe';
  if (/(helm|hood|cap|crown|circlet|visor|bandana|headband|hat|veil|mask|beret)/.test(n)) return 'helm';
  if (/(chest|robe|coat|armor|plate|mail|vest|shirt|jacket|cape|cloak|breastplate|hauberk)/.test(n)) return 'chest';
  if (/(glove|gauntlet|bracer|knuckle|wrap|mittens?|claw)/.test(n)) return 'hands';
  if (/(boot|shoe|sandal|slipper|boot|tread|stomper)/.test(n)) return 'feet';
  if (/(pant|legging|trousers|greaves|kilt)/.test(n)) return 'legs';
  if (/(ring|amulet|pendant|charm|band|talisman|necklace|bracelet|relic|idol|core|orb|totem|sigil|gem|stone|shard)/.test(n)) return 'accessory';
  return 'item';
}

const ITEM_OPENERS = {
  common: [
    'A humble {name}, carried by hunters starting their first dungeon.',
    'Nothing fancy — a {name} forged from common materials.',
    'A basic {name} that does the job, if the job doesn\'t ask too much.',
  ],
  uncommon: [
    'A {name} forged by smiths who have seen a few gates come and go.',
    'A well-made {name} with a single notable feature — it doesn\'t fail.',
    'Standard-issue for a hunter of middling reputation: the {name}.',
  ],
  rare: [
    'A {name} forged from materials that require a real dungeon to obtain.',
    'A {name} that whispers faint songs when its wielder walks in moonlight.',
    'The first of the named weapons — the {name} marks a hunter as serious.',
  ],
  epic: [
    'A {name} forged by a master smith with a grudge against the gods.',
    'A {name} whose edge remembers every battle it has ever tasted.',
    'To hold a {name} is to announce that you are no longer a beginner.',
  ],
  legendary: [
    'A {name} forged in the dying breath of a god. It will outlast its wielder.',
    'A {name} that has killed at least one emperor. Possibly two.',
    'The {name} is a name spoken in battle-halls. Few live to earn it.',
  ],
  mythic: [
    'A {name} that exists only in the libraries of dead civilizations.',
    'A {name} that should not be. Reality flinches when it is drawn.',
    'A {name} that the gods have personally tried to unmake. They failed.',
  ],
};

const MONSTER_OPENERS = [
  'A {name}, drawn from the lower gates. Common, but never kind.',
  'A {name} that has been raiding the surface since before the gates opened.',
  'You can tell a {name} by the smell — iron, rot, and fear.',
];

function generateItemLore(name, rarity) {
  const type = detectItemType(name);
  const element = detectElement(name);
  const openers = ITEM_OPENERS[rarity] || ITEM_OPENERS.common;
  const opener = openers[Math.floor(Math.random() * openers.length)].replace('{name}', name.toLowerCase());
  const elementLine = element
    ? ` Channels ${element} mana — handle with the appropriate caution.`
    : '';
  const typeLine = {
    sword:    'The blade is balanced for a two-handed grip but works one-handed if you must.',
    axe:      'The haft is wrapped in leather that has been there longer than you have.',
    bow:      'The string is made of something the maker refused to name.',
    magic:    'The rune etched on its surface has not been translated yet.',
    blunt:    'The head is heavy enough to leave craters. The handle is light enough to swing.',
    polearm:  'A two-handed weapon meant for formation fighting, but works just as well solo.',
    scythe:   'The blade is curved in a way that makes no sense until you see it in motion.',
    helm:     'Lined with a soft leather interior that no one explains the origin of.',
    chest:    'Worn over a gambeson or a prayer. Both work equally well.',
    hands:    'Fits snugly — too snugly for the wearer to take off without help.',
    feet:     'Muffled, so you can walk the dungeon corridors without waking the whole floor.',
    legs:     'Reinforced at the knee. Hunters have a habit of kneeling on bad news.',
    accessory:'A small, quiet piece. Most of its power happens when you are not looking.',
    item:     'Found in a forgotten cache. Provenance unknown.',
  }[type] || '';
  return `${opener}${elementLine} ${typeLine}`;
}

function generateMonsterLore(name) {
  const opener = MONSTER_OPENERS[Math.floor(Math.random() * MONSTER_OPENERS.length)].replace('{name}', name);
  const element = detectElement(name);
  const elementLine = element
    ? ` Inherently ${element}-aligned — resists that element, weak to its opposite.`
    : '';
  const pack = /\b(wolf|rat|goblin|orc|bat|spider|serpent|slime|imp|drake|elemental|elf)\b/i.test(name)
    ? ' Hunts in groups. Alone, it is a nuisance; in a pack, it is a slaughter.'
    : ' Prefers to engage targets alone. Possibly because it knows what it is.';
  return `${opener}${elementLine}${pack}`;
}

function generateArtifactLore(name) {
  const opener = `The ${name} — `;
  const lines = [
    'one of the relics the first hunters brought back from the inner gates.',
    'a weapon that has decided, over the centuries, who deserves to wield it.',
    'a fragment of a world that ended before humanity was a thought.',
    'a gift from a god who, having given it, immediately regretted the choice.',
  ];
  return opener + lines[Math.floor(Math.random() * lines.length)];
}

function generateClassLore(name) {
  const opener = `The ${name} — `;
  const lines = [
    'a calling chosen by those who refuse to be one thing.',
    'a path that selects its students, not the other way around.',
    'a discipline passed down in hidden halls and unspoken oaths.',
    'a way of war that everyone respects, even its enemies.',
  ];
  return opener + lines[Math.floor(Math.random() * lines.length)];
}

// ═══════════════════════════════════════════════════════════════
// Public API
// ═══════════════════════════════════════════════════════════════

// Get lore for any entity. `kind` is one of:
//   'item' | 'monster' | 'boss' | 'pet' | 'artifact' | 'class'
function getLore(name, kind, extra = {}) {
  if (kind === 'item') {
    return LORE.items[name] || generateItemLore(name, extra.rarity || 'common');
  }
  if (kind === 'monster' || kind === 'boss') {
    return LORE.monsters[name] || generateMonsterLore(name);
  }
  if (kind === 'pet') {
    return LORE.pets[name] || `A small companion — ${name.replace(/_/g, ' ')} — that follows its bonded hunter everywhere.`;
  }
  if (kind === 'artifact') {
    return LORE.artifacts[name] || generateArtifactLore(name);
  }
  if (kind === 'class') {
    return LORE.classes[name] || generateClassLore(name);
  }
  return '';
}

// Format a rarity tag for display
function rarityTag(rarity) {
  const c = ITEM_RARITY_COLORS[rarity] || ITEM_RARITY_COLORS.common;
  return `${c.emoji} *${rarity.toUpperCase()}*`;
}

// Card builder — returns the TEXT block for the second message
// in a two-message card. Caller is responsible for sending the
// image first, then this text.
function buildCardText({ name, kind, rarity, stats, lore, extra }) {
  const lines = [];
  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  if (rarity) lines.push(`${rarityTag(rarity)}  ${name}`);
  else        lines.push(`*${name}*`);
  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('');
  if (kind === 'item' || kind === 'artifact') {
    if (stats) {
      const statKeys = Object.keys(stats).filter((k) => stats[k] != null && stats[k] !== 0);
      if (statKeys.length) {
        const statStr = statKeys
          .map((k) => `\`${k.toUpperCase()}\` +${stats[k]}`)
          .join('  ');
        lines.push(`📊 ${statStr}`);
      }
    }
  }
  if (kind === 'monster' || kind === 'boss') {
    if (extra?.level)    lines.push(`📈 Level: *${extra.level}*`);
    if (extra?.hp)       lines.push(`❤️ HP: *${extra.hp.toLocaleString()}*`);
    if (extra?.atk)      lines.push(`⚔️ ATK: *${extra.atk.toLocaleString()}*`);
    if (extra?.def)      lines.push(`🛡️ DEF: *${extra.def.toLocaleString()}*`);
    if (extra?.abilities) lines.push(`💥 Abilities: ${extra.abilities.join(', ')}`);
  }
  if (kind === 'class') {
    if (extra?.tier)   lines.push(`🎖️ Tier: *${extra.tier.toUpperCase()}*`);
    if (extra?.skills) lines.push(`⚡ Skills: ${extra.skills.join(', ')}`);
  }
  lines.push('');
  if (lore) lines.push(`📜 *Lore:*\n${lore}`);
  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  return lines.join('\n');
}

// Look up the image path for a given entity.
// Returns { path, exists } so the caller can decide whether
// to send the image, send a fallback card, or skip.
function getImage({ kind, name, rarity, tier }) {
  let entry;
  switch (kind) {
    case 'item':     entry = getItemImagePath(name, rarity || 'common'); break;
    case 'pet':      entry = getPetImagePath(name); break;
    case 'monster':  entry = getMonsterImagePath(name); break;
    case 'boss':     entry = getBossImagePath(name); break;
    case 'artifact': entry = getArtifactImagePath(name); break;
    case 'class':    entry = getClassImagePath(name, tier || 'common'); break;
    case 'skin':     entry = getSkinImagePath(name, rarity || 'common'); break;
    default: entry = { path: null, exists: false };
  }
  return entry;
}

module.exports = {
  // Lookups
  getImage,
  getLore,
  buildCardText,
  rarityTag,

  // Path helpers (used by the generator script)
  getItemImagePath,
  getPetImagePath,
  getMonsterImagePath,
  getBossImagePath,
  getArtifactImagePath,
  getClassImagePath,
  getSkinImagePath,

  // Helpers
  slugify,
  findImage,
  invalidateCache,
  ASSET_ROOT,

  // Constants
  ITEM_RARITY_COLORS,
  LORE,
};
