#!/usr/bin/env node
// scripts/split-classes.js
// One-time script: extracts every class from ClassSystem.js's CLASS_DATA,
// plus every monster variant, and writes them to per-file modules under rpg/classes/.
// Run with: node scripts/split-classes.js

'use strict';
const fs = require('fs');
const path = require('path');

const SOURCE = path.join(__dirname, '..', 'rpg', 'utils', 'ClassSystem.js');
const OUT_ROOT = path.join(__dirname, '..', 'rpg', 'classes');

// Tier mapping (from PlayerManager's legacy rarity tags + Senku's 'divine')
const TIERS = {
  Warrior: 'common', Archer: 'common', Rogue: 'common', Mage: 'common',
  Knight: 'common', Monk: 'common', Shaman: 'common', Warlord: 'common',
  Paladin: 'rare', Assassin: 'rare', Ranger: 'rare', BloodKnight: 'rare',
  SpellBlade: 'rare', Elementalist: 'rare', Necromancer: 'rare',
  Berserker: 'legendary', Summoner: 'epic', DragonKnight: 'epic', ShadowDancer: 'epic',
  Phantom: 'legendary', Devourer: 'legendary', Chronomancer: 'legendary',
  Senku: 'divine',
  Monster: 'monster',
};

const TIER_DIR = {
  common: 'common', rare: 'rare', epic: 'epic',
  legendary: 'legendary', divine: 'divine', monster: 'monster',
};

// ── Parse the source file ────────────────────────────────────────────────────
const src = fs.readFileSync(SOURCE, 'utf8');
const dataStart = src.indexOf('const CLASS_DATA = {');
if (dataStart < 0) throw new Error('CLASS_DATA not found');
const dataEnd = src.indexOf('\n};', dataStart);
const dataBlock = src.slice(dataStart, dataEnd);

// Extract CLASS_DATA class blocks using proper brace matching
function extractBlocks(block) {
  const re = /^\s{2}([A-Z][a-zA-Z]+):\s*\{/gm;
  const starts = [...block.matchAll(re)].map(m => ({ name: m[1], pos: m.index }));
  const results = [];
  for (let i = 0; i < starts.length; i++) {
    const start = starts[i].pos;
    let pos = start;
    while (pos < block.length && block[pos] !== '{') pos++;
    if (pos >= block.length) continue;
    let depth = 1;
    pos++;
    let foundEnd = -1;
    while (pos < block.length) {
      const ch = block[pos];
      if (ch === '{') depth++;
      else if (ch === '}') {
        depth--;
        if (depth === 0) { foundEnd = pos; break; }
      } else if (ch === "'" || ch === '"' || ch === '`') {
        const quote = ch;
        pos++;
        while (pos < block.length && block[pos] !== quote) {
          if (block[pos] === '\\') pos++;
          pos++;
        }
      }
      pos++;
    }
    if (foundEnd < 0) continue;
    results.push({ name: starts[i].name, body: block.slice(start, foundEnd + 1) });
  }
  return results;
}

const classBlocks = extractBlocks(dataBlock);
console.log(`Found ${classBlocks.length} class blocks`);

// ── Parse MONSTER_VARIANTS ──────────────────────────────────────────────────
const variantStart = src.indexOf('const MONSTER_VARIANTS = [');
const variantEnd = src.indexOf('\n];', variantStart);
const variantBlock = src.slice(variantStart, variantEnd);
const variantRe = /\{\s*id:'([^']+)',[\s\S]*?name:'([^']+)'[\s\S]*?emoji:'([^']+)'[\s\S]*?lore:'([^']+)'\s*\}/g;
const variants = [...variantBlock.matchAll(variantRe)].map(m => ({
  id: m[1], name: m[2], emoji: m[3], lore: m[4],
}));
console.log(`Found ${variants.length} monster variants`);

// ── Convert a class block body to per-property lines ───────────────────────
// Input: balanced "ClassName: { ... }" with proper brace matching
// Output: just the inner properties (no "ClassName: {" wrapper, no trailing "}")
function bodyToObjectProps(body) {
  let depth = 0;
  let openPos = -1;
  for (let i = 0; i < body.length; i++) {
    if (body[i] === '{') {
      if (depth === 0) openPos = i;
      depth++;
    } else if (body[i] === '}') {
      depth--;
      if (depth === 0) {
        return body.slice(openPos + 1, i).trim();
      }
    }
  }
  return '';
}

// Re-indent the inner properties so they line up under "name: 'X',"
// Source has them at indent-4 (inside CLASS_DATA), we want indent-2
function reindent(props) {
  // Remove leading 2 spaces from each line so everything's flat, then add 2 spaces
  return props.split('\n').map(line => {
    // Strip 2 leading spaces (source had indent of 4, we want 2)
    if (line.startsWith('  ')) return '  ' + line.slice(2);
    return '  ' + line;
  }).join('\n');
}

// ── File template ──────────────────────────────────────────────────────────
function fileForClass(className, propsText) {
  const now = new Date().toISOString();
  return `// ═══════════════════════════════════════════════════════════════
// Astra — ${className} class
// Auto-generated by scripts/split-classes.js on ${now}
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: '${className}',
${reindent(propsText)}
};
`;
}

function fileForVariant(v) {
  return `// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: ${v.name}
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    '${v.id}',
  name:  '${v.name}',
  emoji: '${v.emoji}',
  lore:  ${JSON.stringify(v.lore)},
};
`;
}

// ── Write class files ──────────────────────────────────────────────────────
for (const { name, body } of classBlocks) {
  const tier = TIERS[name];
  if (!tier) {
    console.warn(`⚠️  No tier mapping for ${name}, skipping`);
    continue;
  }
  const dir = path.join(OUT_ROOT, TIER_DIR[tier]);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const filePath = path.join(dir, `${name}.js`);
  const props = bodyToObjectProps(body);
  fs.writeFileSync(filePath, fileForClass(name, props));
  console.log(`✅ Wrote ${filePath}`);
}

// ── Write monster variant files ───────────────────────────────────────────
const monsterDir = path.join(OUT_ROOT, 'monster');
if (!fs.existsSync(monsterDir)) fs.mkdirSync(monsterDir, { recursive: true });
for (const v of variants) {
  const filePath = path.join(monsterDir, `${v.id}.js`);
  fs.writeFileSync(filePath, fileForVariant(v));
}
console.log(`✅ Wrote ${variants.length} monster variant files`);

console.log('\n🎉 Done!');
