// ═══════════════════════════════════════════════════════════════
// Astra — DragonKnight class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.301Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'DragonKnight',
  emoji: '🐉',
    lore: 'Bonded with dragonkind. Feared by both worlds.',
    maxBonuses: { hp: 140, atk: 45, def: 30, speed: 15, maxEnergy: 35, magicPower: 20 },
    skills: [
      { name: 'Dragon Roar',   type: 'debuff',  maxPotency: 40,  desc: 'All enemies: ATK -{p}%, DEF -{p/2}% for 3 turns' },
      { name: 'Dragon Strike', type: 'damage',  maxPotency: 260, desc: 'Flame-enhanced hit: {p}% ATK as fire damage' },
      { name: 'Scale Armor',   type: 'passive', maxPotency: 25,  desc: 'Physical damage reduced by {p}%' },
    ],
};
