// ═══════════════════════════════════════════════════════════════
// Astra — ShadowDancer class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.302Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'ShadowDancer',
  emoji: '🌑',
    lore: 'Moves between shadows. Strikes from impossible angles.',
    maxBonuses: { hp: 50, atk: 45, def: 8, speed: 55, maxEnergy: 45, critChance: 12 },
    skills: [
      { name: 'Shadow Step',    type: 'buff',    maxPotency: 100, desc: 'Untargetable for 1 turn, next attack: +{p}% crit' },
      { name: 'Umbral Slash',   type: 'damage',  maxPotency: 240, desc: 'Attacks from all shadows simultaneously: {p}% ATK' },
      { name: 'Shade Form',     type: 'passive', maxPotency: 30,  desc: 'Passively reduces visibility — dodge +{p}%' },
    ],
};
