// ═══════════════════════════════════════════════════════════════
// Astra — Summoner class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.301Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Summoner',
  emoji: '🌟',
    lore: 'The army is always one command away.',
    maxBonuses: { hp: 60, atk: 25, def: 10, speed: 10, maxEnergy: 80, magicPower: 40 },
    skills: [
      { name: 'Summon Shade',  type: 'damage',  maxPotency: 160, desc: 'Conjures a shade that attacks for {p}% Magic Power' },
      { name: 'Pack Tactics',  type: 'passive', maxPotency: 30,  desc: 'Each active summon grants +{p}% total damage' },
      { name: 'Spirit Surge',  type: 'buff',    maxPotency: 50,  desc: 'All summons deal {p}% bonus damage for 2 turns' },
    ],
};
