// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Abyssal Shark
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'abyssal_shark',
  name:  'Abyssal Shark',
  emoji: '🦈',
  lore:  "Swims through solid matter like water. Evolved in the dimensional abyss.",
};
