// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Acid Mantis
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'acid_mantis',
  name:  'Acid Mantis',
  emoji: '🧪',
  lore:  "Precision strikes coated in acid. Cuts through armor and the metal beneath.",
};
