// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Acid Toad
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'acid_toad',
  name:  'Acid Toad',
  emoji: '🐸',
  lore:  "Secretes acid instead of sweat. The area around it permanently smells wrong.",
};
