// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Ash Serpent
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'ash_serpent',
  name:  'Ash Serpent',
  emoji: '🔥',
  lore:  "Moves through ash fields undetected. Entire villages have learned this too late.",
};
