// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Blood Toad
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'blood_toad',
  name:  'Blood Toad',
  emoji: '🩸',
  lore:  "Absorbs the blood of the fallen to increase its size. Some have grown city-sized.",
};
