// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Blood Bat
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'blood_bat',
  name:  'Blood Bat',
  emoji: '🦇',
  lore:  "Drains entire bloodlines in a night. It has been alive for twenty centuries.",
};
