// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Bone Stalker
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'bone_stalker',
  name:  'Bone Stalker',
  emoji: '🦴',
  lore:  "Made entirely of bones from its prey. It is still growing.",
};
