// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Bone Colossus
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'bone_colossus',
  name:  'Bone Colossus',
  emoji: '💀',
  lore:  "An amalgam of thousands of fallen warriors, held together by dark will.",
};
