// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Bone Dragon
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'bone_dragon',
  name:  'Bone Dragon',
  emoji: '🦴',
  lore:  "The remains of a dragon reanimated by its own residual will to kill.",
};
