// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Chaos Dragon
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'chaos_dragon',
  name:  'Chaos Dragon',
  emoji: '🐉',
  lore:  "The last surviving creature from the Chaos Age. It has outlasted everything else. Intentionally.",
};
