// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Chaos Beetle
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'chaos_beetle',
  name:  'Chaos Beetle',
  emoji: '🔮',
  lore:  "Contains a fragment of the Chaos God. It does not know this. It acts on it anyway.",
};
