// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Mana Stone Spider
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'crystal_spider',
  name:  'Mana Stone Spider',
  emoji: '💎',
  lore:  "Webs made of crystallized magic. Cuts enchantments on contact.",
};
