// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Dark Mantis
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'dark_mantis',
  name:  'Dark Mantis',
  emoji: '🦗',
  lore:  "Faster than eyesight. The strike lands before the intent forms.",
};
