// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Dark Crab
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'dark_crab',
  name:  'Dark Crab',
  emoji: '🦀',
  lore:  "Its shell absorbs damage and converts it into counterforce.",
};
