// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Death Hound
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'death_hound',
  name:  'Death Hound',
  emoji: '🦴',
  lore:  "The hound that escorts the dying. It has followed many hunters.",
};
