// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Decay Wraith
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'decay_wraith',
  name:  'Decay Wraith',
  emoji: '☠️',
  lore:  "Ages whatever it touches by decades per second.",
};
