// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Dusk Crow
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'dusk_crow',
  name:  'Dusk Crow',
  emoji: '🐦',
  lore:  "Arrives at sunset. Leaves at sunrise. Whatever it fed on is never found.",
};
