// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Ember Wolf
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'ember_wolf',
  name:  'Ember Wolf',
  emoji: '🔥',
  lore:  "Runs so fast it ignites. Runs faster because of the ignition.",
};
