// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Feral Bear
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'feral_bear',
  name:  'Feral Bear',
  emoji: '🐻',
  lore:  "A bear that consumed a dungeon core. It does not stop. Not for anything.",
};
