// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Flesh Eater
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'flesh_eater',
  name:  'Flesh Eater',
  emoji: '🫀',
  lore:  "Does not kill. Consumes. The difference matters greatly to survivors.",
};
