// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Frost Crawler
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'frost_crawler',
  name:  'Frost Crawler',
  emoji: '❄️',
  lore:  "Freezes the ground it walks on. Has been walking across the continent for decades.",
};
