// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Frost Yeti
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'frost_yeti',
  name:  'Frost Yeti',
  emoji: '🏔️',
  lore:  "Guardian of the highest peaks. It has never lost a fight at altitude.",
};
