// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Goblin Mutant
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'goblin_mutant',
  name:  'Goblin Mutant',
  emoji: '👺',
  lore:  "A goblin warped by dungeon mana. Cunning, feral, and twice as dangerous.",
};
