// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Hollow Knight
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'hollow_knight',
  name:  'Hollow Knight',
  emoji: '⚔️',
  lore:  "A fallen paladin with nothing left inside but the mission.",
};
