// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Ice Ghoul
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'ice_ghoul',
  name:  'Ice Ghoul',
  emoji: '🧊',
  lore:  "Preserved by eternal frost. It has been hungry since the first ice age.",
};
