// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Infernal Drake
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'infernal_drake',
  name:  'Infernal Drake',
  emoji: '🔥',
  lore:  "A minor dragon corrupted by hellfire. Its breath melts steel.",
};
