// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Iron Golem
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'iron_golem',
  name:  'Iron Golem',
  emoji: '🤖',
  lore:  "Built to guard an ancient vault. The vault is long gone. It still guards.",
};
