// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Iron Scorpion
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'iron_scorpion',
  name:  'Iron Scorpion',
  emoji: '🦂',
  lore:  "Its exoskeleton deflects all non-magical attacks. Its venom dissolves magical ones.",
};
