// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Lava Crab
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'lava_crab',
  name:  'Lava Crab',
  emoji: '🦀',
  lore:  "Lives inside active volcanoes. The lava is how it stays cool.",
};
