// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Magma Beetle
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'magma_beetle',
  name:  'Magma Beetle',
  emoji: '🪲',
  lore:  "Its shell is a natural furnace. Being crushed by it is considered lucky — it is faster.",
};
