// ═══════════════════════════════════════════════════════════════
// Astra — Monster class
// Auto-generated by scripts/split-classes.js on 2026-07-24T18:50:22.302Z
// Source: rpg/utils/ClassSystem.js (legacy inlined class data)
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  name: 'Monster',
  emoji: '👹',
    lore: 'You did not awaken as a hunter. You awakened as the prey.',
    maxBonuses: { hp: 200, atk: 60, def: 30, speed: 20, maxEnergy: 20 },
    skills: [
      { name: 'Primal Strike',   type: 'damage',  maxPotency: 280, desc: 'Savage hit: {p}% ATK, 40% chance to apply bleed' },
      { name: 'Monster Roar',    type: 'debuff',  maxPotency: 35,  desc: 'Target ATK -{p}%, fills them with primal fear' },
      { name: 'Mutant Physiology',type:'passive', maxPotency: 20,  desc: 'Reduces all incoming damage by {p}%, regenerate {p/4} HP/turn' },
    ],
};
