// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Mud Titan
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'mud_titan',
  name:  'Mud Titan',
  emoji: '🟫',
  lore:  "Pulls entire armies underground. It has been fighting a war beneath the earth for centuries.",
};
