// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Plague Rat
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'plague_rat',
  name:  'Plague Rat',
  emoji: '🐀',
  lore:  "Every bite carries seventeen distinct curses. Fourteen are lethal.",
};
