// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Plague Bat
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'plague_bat',
  name:  'Plague Bat',
  emoji: '🦠',
  lore:  "Each wing-flap spreads airborne variants of the dungeon plague.",
};
