// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Sand Worm
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'sand_worm',
  name:  'Sand Worm',
  emoji: '🪱',
  lore:  "Ancient desert god. Villages that angered it vanished — ground and all.",
};
