// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Shadow Mantis
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'shadow_mantis',
  name:  'Shadow Mantis',
  emoji: '🗡️',
  lore:  "Hunts exclusively in shadow. Its strikes are so precise they leave no exit wound.",
};
