// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Shadow Wraith
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'shadow_wraith',
  name:  'Shadow Wraith',
  emoji: '👻',
  lore:  "Solid darkness given form. It passes through walls to reach its prey.",
};
