// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Spectral Wolf
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'spectral_wolf',
  name:  'Spectral Wolf',
  emoji: '🌫️',
  lore:  "Hunts across the barrier between life and death simultaneously.",
};
