// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Stone Hydra
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'stone_hydra',
  name:  'Stone Hydra',
  emoji: '🪨',
  lore:  "Cut a stone head and it becomes two. The stone is immune to fire. The flesh beneath is not.",
};
