// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Stone Troll
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'stone_troll',
  name:  'Stone Troll',
  emoji: '🪨',
  lore:  "Skin like granite. Regenerates from seemingly fatal blows.",
};
