// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Storm Hawk
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'storm_hawk',
  name:  'Storm Hawk',
  emoji: '🦅',
  lore:  "Rides lightning. Rides it literally — it generates storms for transportation.",
};
