// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Thunder Ape
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'thunder_ape',
  name:  'Thunder Ape',
  emoji: '🦍',
  lore:  "Every punch crackles. Every roar deafens. Every appearance ends battles.",
};
