// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Thunder Lizard
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'thunder_lizard',
  name:  'Thunder Lizard',
  emoji: '⚡',
  lore:  "A relic from before mammals. Survived because nothing could kill it.",
};
