// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Thunder Golem
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'thunder_golem',
  name:  'Thunder Golem',
  emoji: '⚡',
  lore:  "Lightning given solid form by a reckless mage two centuries ago. Still angry.",
};
