// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Toxic Serpent
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'toxic_serpent',
  name:  'Toxic Serpent',
  emoji: '🐍',
  lore:  "Its venom dissolves not just flesh — it dissolves memories of the victim.",
};
