// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Venom Hydra
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'venom_hydra',
  name:  'Venom Hydra',
  emoji: '🐲',
  lore:  "Cut one head and three replace it. Each new head is more intelligent than the last.",
};
