// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Void Stalker
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'void_stalker',
  name:  'Void Stalker',
  emoji: '🌌',
  lore:  "Tracks prey across dimensions. There is no realm it cannot follow you into.",
};
