// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Void Colossus
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'void_colossus',
  name:  'Void Colossus',
  emoji: '🌌',
  lore:  "A titan from the void. Walked into this world looking for something. Still looking.",
};
