// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Void Spider
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'void_spider',
  name:  'Void Spider',
  emoji: '🕷️',
  lore:  "Spins webs between dimensions. Prey disappear before they understand what caught them.",
};
