// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Void Moth
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'void_moth',
  name:  'Void Moth',
  emoji: '🦋',
  lore:  "Beautiful. Drawn to strong mana. Drains it completely.",
};
