// ═══════════════════════════════════════════════════════════════
// Astra — Monster variant: Wolf Hybrid
// Auto-generated by scripts/split-classes.js
// ═══════════════════════════════════════════════════════════════

'use strict';

module.exports = {
  id:    'wolf_hybrid',
  name:  'Wolf Hybrid',
  emoji: '🐺',
  lore:  "Part hunter, part beast. The wolf in them never sleeps.",
};
